#!/usr/bin/env python3


def calculate_age(birth_year, current_year):
    # Calculate age by subtracting the birth year from the current year
    age = current_year - birth_year
    return age
try:
    birth_year = int(input("Enter the birth year: "))
    current_year = int(input("Enter the current year: "))
    age = calculate_age(birth_year, current_year)
    print(f"You are {age} years old.")

except ValueError:
    print("Please enter an int")


def helloWorld():
    print('Hello World')

helloWorld()
